Server:
  RunMode: debug
  HttpPort: 8805
  ReadHeaderTimeout: 30 # unit: second
  ReadTimeout: 30 # unit: second
  WriteTImeout: 30 # unit: second
  # MaxHeaderBytes: 1024  

App:
  Name: seafarer
  PageSize: 10
  MaxPageSize: 100

Logger:
  Level: debug
  Dir: ./logs
  Format: text  # json or text
  Filename: seafarer.log
  MaxSize: 1000  # unit: MB
  MaxBackups: 5
  MaxAge: 3  # unit: day
  Compress: true

Sqlite:
  Dir: ./db
  Filename: seafarer.db
  
